version: '3.8'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - '3306:3306'
    volumes:
      - db-data:/var/lib/mysql

  api:
    build: .
    ports:
      - '4000:4000'
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql://user:password@db:3306/mydb
    volumes:
      - .:/app

volumes:
  db-data:
